name: ammodepot
version: '1.0'
config-version: 2

profile: redshift_profile

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ammodepot:
    staging:
      +materialized: view
      +schema: staging
    gold:
      +materialized: table
      +schema: gold

