ammodepot_lakehouse:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: ':memory:'
      extensions:
        - httpfs
        - iceberg
        - aws
      secrets:
        - type: s3
          name: glue_s3_secret
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID', '') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY', '') }}"
          region: us-east-1
      settings:
        http_timeout: 600000
      attach:
        - path: '746669199691'
          alias: glue
          type: iceberg
          secret: glue_s3_secret
          options:
            endpoint_type: GLUE
      threads: 4
