# models/sources.yml
version: 2

sources:
  - name: bronze
    database: ammodepot
    schema: bronze
    tables:
      - name: sales_order
      - name: sales_order_item
      - name: sales_order_address
      - name: customer_entity
      - name: customer_group
      - name: quote
      - name: quote_shipping_rate
      - name: quote_address
      - name: catalog_product_entity
      - name: catalog_product_entity_varchar
      - name: catalog_product_entity_text
      - name: catalog_product_entity_int
      - name: catalog_product_entity_decimal
      - name: eav_attribute
      - name: eav_attribute_option_value
      - name: catalog_category_product
      - name: catalog_category_entity_varchar
      - name: catalog_product_super_link
      - name: eav_attribute_set
      - name: sales_shipment_grid
      - name: vendor
      - name: store

  - name: bronze
    database: bronze
    schema: bronze
    tables:
      - name: plugininfo
      - name: ship
      - name: shipcarton
      - name: so
      - name: soitem
      - name: product
      - name: part
      - name: partcost
      - name: uomconversion
      - name: vendorparts
      - name: carrierservice
      - name: inventorylog
      - name: tablereference

