redshift_profile:
  target: dev
  outputs:
    dev:
      type: redshift
      host: airbyte-project-redshift-cluster.chaiaxiqde3z.us-east-1.redshift.amazonaws.com
      user: admin
      password: "QYt5eRJUEzqQYw6#DBj8"
      port: 5439
      dbname: gold_db
      schema: gold
      threads: 4
      sslmode: prefer
