{{
  config(
    materialized = 'view',
    schema = 'silver'
  )
}}

WITH source_data AS (
    SELECT 
        id,
        num,
        upc,
        len,
        width,
        height,
        weight,
        typeid,
        uomid,
        taxid,
        details,
        stdcost,
        revision,
        leadtime,
        alertnote,
        sizeuomid,
        activeflag,
        abccode,
        datecreated,
        description,
        partclassid,
        weightuomid,
        accountingid,
        configurable,
        defaultbomid,
        receivingtol,
        trackingflag,
        cogsaccountid,
        cyclecounttol,
        controlledflag,
        scrapaccountid,
        serializedflag,
        consumptionrate,
        pickinuomofpart,
        datelastmodified,
        defaultproductid,
        alwaysmanufacture,
        varianceaccountid,
        inventoryaccountid,
        adjustmentaccountid,
        defaultpoitemtypeid,
        defaultoutsourcedreturnitemid,
        url,
        lastchangeduser,
        customfields
    FROM 
        {{ source('fishbowl', 'part') }}
    WHERE 
        _ab_cdc_deleted_at IS NULL
)

SELECT 
    id AS part_id,
    num AS part_number,
    upc AS upc_code,
    description AS part_description,
    typeid AS part_type_id,
    activeflag AS is_active,
    abccode AS abc_code,
    len AS length,
    width AS width,
    height AS height,
    weight AS weight,
    sizeuomid AS size_uom_id,
    weightuomid AS weight_uom_id,
    uomid AS default_uom_id,
    taxid AS tax_id,
    details AS part_details,
    stdcost AS standard_cost,
    revision AS revision_number,
    leadtime AS lead_time_days,
    alertnote AS alert_note,
    datecreated AS date_created,
    partclassid AS part_class_id,
    accountingid AS accounting_id,
    configurable AS is_configurable,
    defaultbomid AS default_bom_id,
    receivingtol AS receiving_tolerance,
    trackingflag AS has_tracking,
    cogsaccountid AS cogs_account_id,
    cyclecounttol AS cycle_count_tolerance,
    controlledflag AS is_controlled,
    scrapaccountid AS scrap_account_id,
    serializedflag AS is_serialized,
    consumptionrate AS consumption_rate,
    pickinuomofpart AS pick_in_uom_of_part,
    datelastmodified AS date_last_modified,
    defaultproductid AS default_product_id,
    alwaysmanufacture AS always_manufacture,
    varianceaccountid AS variance_account_id,
    inventoryaccountid AS inventory_account_id,
    adjustmentaccountid AS adjustment_account_id,
    defaultpoitemtypeid AS default_po_item_type_id,
    defaultoutsourcedreturnitemid AS default_outsourced_return_item_id,
    url AS part_url,
    lastchangeduser AS last_changed_user,
    customfields AS custom_fields
FROM 
    source_data