with source_data as (

    select
        -- Select ALL columns from the source DDL
        state,
        status,
        weight,
        quote_id,
        store_id,
        subtotal,
        entity_id,
        ga_cookie,
        remote_ip,
        route_fee,
        total_due,
        --carrier_id,
        created_at,
        email_sent,
        is_virtual,
        order_size,
        send_email,
        store_name,
        tax_amount,
        total_paid,
        updated_at,
        coupon_code,
        customer_id,
        grand_total,
        location_id,
        --carrier_type,
        customer_dob,
        ext_order_id,
        ga_timestamp,
        increment_id,
        protect_code,
        tax_canceled,
        tax_invoiced,
        tax_refunded,
        base_subtotal,
        customer_note,
        ga_session_id,
        route_tax_fee,
        base_total_due,
        customer_email,
        edit_increment,
        route_order_id,
        total_canceled,
        total_invoiced,
        total_refunded,
        aw_afptc_amount,
        base_tax_amount,
        base_total_paid,
        customer_gender,
        customer_prefix,
        customer_suffix,
        customer_taxvat,
        discount_amount,
        ext_customer_id,
        gift_message_id,
        shipping_amount,
        shipping_method,
        x_forwarded_for,
        applied_rule_ids,
        base_grand_total,
        coupon_rule_name,
        destination_type,
        quote_address_id,
        route_is_insured,
        total_item_count,
        aw_afptc_invoiced,
        aw_afptc_refunded,
        base_tax_canceled,
        base_tax_invoiced,
        base_tax_refunded,
        customer_group_id,
        customer_is_guest,
        customer_lastname,
        discount_canceled,
        discount_invoiced,
        discount_refunded,
        hold_before_state,
        relation_child_id,
        shipping_canceled,
        shipping_incl_tax,
        shipping_invoiced,
        shipping_refunded,
        subtotal_canceled,
        subtotal_incl_tax,
        subtotal_invoiced,
        subtotal_refunded,
        total_qty_ordered,
        validation_status,
        aw_giftcard_amount,
        base_currency_code,
        base_to_order_rate,
        billing_address_id,
        can_ship_partially,
        customer_firstname,
        hold_before_status,
        relation_parent_id,
        store_to_base_rate,
        adjustment_negative,
        adjustment_positive,
        base_to_global_rate,
        base_total_canceled,
        base_total_invoiced,
        base_total_refunded,
        customer_middlename,
        order_currency_code,
        sent_to_measurement,
        shipping_address_id,
        shipping_tax_amount,
        store_currency_code,
        store_to_order_rate,
        applied_restrictions,
        aw_afptc_uses_coupon,
        aw_giftcard_invoiced,
        aw_giftcard_refunded,
        base_aw_afptc_amount,
        base_discount_amount,
        base_shipping_amount,
        customer_note_notify,
        discount_description,
        global_currency_code,
        is_sportsouth_failed,
        is_sportssouth_order,
        last_tracking_update,
        shipping_description,
        original_increment_id,
        shipping_tax_refunded,
        sports_south_order_id,
        total_online_refunded,
        base_aw_afptc_invoiced,
        base_aw_afptc_refunded,
        base_discount_canceled,
        base_discount_invoiced,
        base_discount_refunded,
        base_shipping_canceled,
        base_shipping_incl_tax,
        base_shipping_invoiced,
        base_shipping_refunded,
        base_subtotal_canceled,
        base_subtotal_incl_tax,
        base_subtotal_invoiced,
        base_subtotal_refunded,
        base_total_qty_ordered,
        relation_child_real_id,
        total_offline_refunded,
        base_aw_giftcard_amount,
        can_ship_partially_item,
        payment_auth_expiration,
        relation_parent_real_id,
        base_adjustment_negative,
        base_adjustment_positive,
        base_shipping_tax_amount,
        base_total_invoiced_cost,
        shipping_discount_amount,
        base_aw_giftcard_invoiced,
        base_aw_giftcard_refunded,
        base_shipping_tax_refunded,
        base_total_online_refunded,
        --carriergroup_shipping_html,
        sports_south_accs_order_id,
        sports_south_ship_order_id,
        base_total_offline_refunded,
        forced_shipment_with_invoice,
        payment_authorization_amount,
        base_shipping_discount_amount,
        --carriergroup_shipping_details,
        mp_smtp_email_marketing_synced,
        discount_tax_compensation_amount,
        discount_tax_compensation_invoiced,
        discount_tax_compensation_refunded,
        base_discount_tax_compensation_amount,
        mp_smtp_email_marketing_order_created,
        base_discount_tax_compensation_invoiced,
        base_discount_tax_compensation_refunded,
        shipping_discount_tax_compensation_amount,
        base_shipping_discount_tax_compensation_amnt,

        -- Airbyte CDC columns for filtering/metadata (kept for reference if needed)
        _ab_cdc_cursor,
        _ab_cdc_log_pos,
        _ab_cdc_log_file,
        _ab_cdc_deleted_at,
        _ab_cdc_updated_at

        -- Columns excluded: _AIRBYTE_RAW_ID, _AIRBYTE_EXTRACTED_AT, _AIRBYTE_META, _AIRBYTE_GENERATION_ID

    from
        {{ source('magento', 'sales_order') }}
    where
        _ab_cdc_deleted_at is null
)

select
    -- Renaming and Casting applied where appropriate
    entity_id as order_id,
    increment_id as order_increment_id,
    store_id,
    customer_id,
    quote_id,
    billing_address_id,
    shipping_address_id,
    ext_order_id as external_order_id,
    ext_customer_id as external_customer_id,

    state as order_state,
    status as order_status,

    created_at,
    updated_at,
    customer_dob,
    last_tracking_update,

    customer_email,
    customer_firstname,
    customer_lastname,
    customer_prefix,
    customer_middlename,
    customer_suffix,
    customer_gender,
    customer_group_id,
    cast(customer_is_guest as boolean) as is_customer_guest,
    customer_note,
    cast(customer_note_notify as boolean) as should_notify_customer_note,
    customer_taxvat,

    store_name,

    -- Financials (Order Currency)
    order_currency_code,
    grand_total,
    subtotal,
    subtotal_incl_tax,
    shipping_amount,
    shipping_incl_tax,
    tax_amount,
    discount_amount,
    total_paid,
    total_refunded,
    total_due,
    total_canceled,
    aw_giftcard_amount,
    adjustment_positive,
    adjustment_negative,
    tax_canceled,
    tax_invoiced,
    tax_refunded,
    discount_canceled,
    discount_invoiced,
    discount_refunded,
    shipping_canceled,
    shipping_invoiced,
    shipping_refunded,
    subtotal_canceled,
    subtotal_invoiced,
    subtotal_refunded,
    aw_afptc_amount,
    aw_afptc_invoiced,
    aw_afptc_refunded,
    aw_giftcard_invoiced,
    aw_giftcard_refunded,
    total_online_refunded,
    total_offline_refunded,
    shipping_tax_amount,
    shipping_tax_refunded,
    shipping_discount_amount,
    discount_tax_compensation_amount,
    discount_tax_compensation_invoiced,
    discount_tax_compensation_refunded,
    shipping_discount_tax_compensation_amount,

    -- Financials (Base Currency)
    base_currency_code,
    base_grand_total,
    base_subtotal,
    base_subtotal_incl_tax,
    base_shipping_amount,
    base_shipping_incl_tax,
    base_tax_amount,
    base_discount_amount,
    base_total_paid,
    base_total_refunded,
    base_total_due,
    base_total_canceled,
    base_aw_giftcard_amount,
    base_adjustment_positive,
    base_adjustment_negative,
    base_tax_canceled,
    base_tax_invoiced,
    base_tax_refunded,
    base_discount_canceled,
    base_discount_invoiced,
    base_discount_refunded,
    base_shipping_canceled,
    base_shipping_invoiced,
    base_shipping_refunded,
    base_subtotal_canceled,
    base_subtotal_invoiced,
    base_subtotal_refunded,
    base_aw_afptc_amount,
    base_aw_afptc_invoiced,
    base_aw_afptc_refunded,
    base_aw_giftcard_invoiced,
    base_aw_giftcard_refunded,
    base_total_online_refunded,
    base_total_offline_refunded,
    base_shipping_tax_amount,
    base_shipping_tax_refunded,
    base_shipping_discount_amount,
    base_total_invoiced_cost,
    base_discount_tax_compensation_amount,
    base_discount_tax_compensation_invoiced,
    base_discount_tax_compensation_refunded,
    base_shipping_discount_tax_compensation_amnt,

    -- Shipping Details
    shipping_method,
    shipping_description,
    weight,
    total_qty_ordered,
    total_item_count,
    cast(can_ship_partially as boolean) as can_ship_partially,
    cast(can_ship_partially_item as boolean) as can_ship_partially_item,
    --carrier_id,
    --carrier_type,
    destination_type,
    --carriergroup_shipping_html,
    --carriergroup_shipping_details,
    cast(forced_shipment_with_invoice as boolean) as has_forced_shipment_with_invoice,

    -- Billing/Payment Details
    coupon_code,
    applied_rule_ids,
    coupon_rule_name,
    discount_description,
    payment_auth_expiration, -- Assuming this NUMBER is a Unix timestamp or similar
    payment_authorization_amount,
    protect_code,

    -- Flags & Settings
    cast(is_virtual as boolean) as is_virtual_order,
    cast(email_sent as boolean) as is_email_sent,
    cast(send_email as boolean) as should_send_email,
    validation_status,
    cast(sent_to_measurement as boolean) as is_sent_to_measurement,
    cast(aw_afptc_uses_coupon as boolean) as aw_afptc_uses_coupon, -- Advanced Promotions extension flag

    -- Technical/Metadata
    remote_ip,
    x_forwarded_for,
    global_currency_code,
    store_to_base_rate,
    store_to_order_rate,
    base_to_global_rate,
    base_to_order_rate,
    ga_cookie,
    ga_timestamp,
    ga_session_id,
    _ab_cdc_cursor,
    _ab_cdc_log_pos,
    _ab_cdc_log_file,
    _ab_cdc_updated_at,

    -- Relationship IDs
    quote_address_id,
    relation_child_id,
    relation_parent_id,
    relation_child_real_id,
    relation_parent_real_id,
    gift_message_id,

    -- Order Attributes
    order_size,
    edit_increment,
    original_increment_id,

    -- Hold Status
    hold_before_state,
    hold_before_status,

    -- System Specific Fields (kept as requested)
    route_fee,
    route_tax_fee,
    route_order_id,
    cast(route_is_insured as boolean) as is_route_insured,
    applied_restrictions,
    cast(is_sportsouth_failed as boolean) as is_sportsouth_failed,
    cast(is_sportssouth_order as boolean) as is_sportssouth_order,
    sports_south_order_id,
    sports_south_accs_order_id,
    sports_south_ship_order_id,
    cast(mp_smtp_email_marketing_synced as boolean) as is_mp_smtp_email_marketing_synced,
    cast(mp_smtp_email_marketing_order_created as boolean) as is_mp_smtp_email_marketing_order_created,
    location_id -- Often related to inventory source/location

    -- Note: _AB_CDC_DELETED_AT is used in the WHERE clause and typically not selected in the final output.

from
    source_data
