select
    vendor_id                    as VENDOR_ID,
    vendor_name                  as VENDOR_NAME,
    vendor_note                  as VENDOR_NOTE,
    vendor_url                   as VENDOR_URL,
    lead_time_days               as LEAD_TIME_DAYS,
    status_id                    as STATUS_ID,
    account_id                   as ACCOUNT_ID,
    sysuser_id                   as SYSUSER_ID,
    tax_rate_id                  as TAX_RATE_ID,
    account_number               as ACCOUNT_NUMBER,
    is_active                    as IS_ACTIVE,
    currency_id                  as CURRENCY_ID,
    credit_limit                 as CREDIT_LIMIT,
    date_entered                 as DATE_ENTERED,
    accounting_id                as ACCOUNTING_ID,
    currency_rate                as CURRENCY_RATE,
    custom_fields                as CUSTOM_FIELDS,
    accounting_hash              as ACCOUNTING_HASH,
    minimum_order_amount         as MINIMUM_ORDER_AMOUNT,
    last_changed_user            as LAST_CHANGED_USER,
    date_last_modified           as DATE_LAST_MODIFIED,
    default_carrier_id           as DEFAULT_CARRIER_ID,
    default_ship_terms_id        as DEFAULT_SHIP_TERMS_ID,
    default_payment_terms_id     as DEFAULT_PAYMENT_TERMS_ID,
    default_carrier_service_id   as DEFAULT_CARRIER_SERVICE_ID
from {{ ref('fishbowl_vendors') }}
