name: 'ammodepot'
version: '1.0.0'

# ← this is required when you use per‑model configs
config-version: 2

profile: 'ammodepot'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ammodepot:
    # default schema if a model isn’t in bronze/silver/gold
    +schema: "{{ target.schema }}"
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table