name: 'ammodepot'
version: '1.0.0'

config-version: 2

profile: 'ammodepot'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  # Default: any model not in silver/ or gold/ will go to target.schema
  ammodepot:
    +schema: "{{ target.schema }}"

  # All files in models/silver/ (and subfolders) become tables in schema 'silver'
  silver:
    +schema: silver
    +materialized: table

  # All files in models/gold/ (and subfolders) become tables in schema 'gold'
  gold:
    +schema: gold
    +materialized: table
